import { join } from 'node:path'
import { appendNote } from '../storage/notes.js'
import { TRACKS } from './capture.js'
import { languagesIn, mergeTracks } from './merge.js'
import { downloadModel, isModelReady, modelPath } from './model.js'
import { composeNote, writeNote } from './note.js'
import { askVia, resolveProvider } from './provider.js'
import { classifyTracks } from './silence.js'
import { summariseMeeting } from './summarise.js'
import { dropNonSpeech, transcribe } from './whisper.js'

/**
 * Everything that happens after the audio stops: transcribe, merge, summarise, write.
 *
 * Kept apart from the recording so it can be run against an existing recording — which
 * is also how a meeting gets recovered if the app is quit before processing finishes.
 */
export const processRecording = async ({
  dataDir,
  dir,
  capturedTracks,
  startedAt,
  endedAt,
  title = '',
  language = 'auto',
  allowCloud = false,
  extraWarnings = [],
  phase = () => {},
}) => {
  const { audible, warnings: found } = classifyTracks(capturedTracks)
  const warnings = [...extraWarnings, ...found]
  if (audible.length === 0) {
    phase('done', { note: null, warnings })
    return { dir, warnings, note: null, segments: 0 }
  }

  if (!(await isModelReady(dataDir))) {
    phase('downloading-model', { ratio: 0 })
    await downloadModel({
      dataDir,
      onProgress: ({ ratio, received, total }) =>
        phase('downloading-model', { ratio, received, total }),
    })
  }

  const model = modelPath(dataDir)
  const transcripts = []
  for (const track of audible) {
    phase('transcribing', { track: track.name })
    const result = await transcribe({
      wavPath: join(dir, TRACKS[track.name]),
      modelPath: model,
      language,
    })
    transcripts.push({
      name: track.name,
      language: result.language,
      segments: dropNonSpeech(result.segments),
    })
  }

  const segments = mergeTracks(transcripts)
  if (segments.length === 0) warnings.push('No speech was recognised in the recording.')

  let summary = null
  let provider = null
  if (segments.length > 0) {
    provider = await resolveProvider({ allowCloud })
    if (provider.kind === 'none') {
      warnings.push(
        `No summary was written: ${provider.reason}${provider.hint ? ` (${provider.hint})` : ''}`,
      )
    } else {
      phase('summarising', { provider: provider.label, isLocal: provider.isLocal })
      if (!provider.isLocal) {
        warnings.push(
          `The summary was generated by ${provider.label}, so the transcript was sent ` +
            `off this Mac. ${provider.localReason ?? ''}`.trim(),
        )
      }
      try {
        summary = await summariseMeeting({ ask: askVia(provider), segments, title })
      } catch (error) {
        // The transcript is most of the value; losing it because a summariser failed
        // would be indefensible.
        warnings.push(`The summary failed: ${error.message}`)
      }
    }
  }

  const notePath = await writeNote({
    dir,
    markdown: composeNote({
      title,
      startedAt,
      endedAt,
      languages: languagesIn(transcripts),
      segments,
      summary,
      warnings,
    }),
  })

  // A line in the daily notes too, so a meeting is findable where every other note is.
  await appendNote({
    dataDir,
    at: endedAt,
    text: `Meeting recorded: ${title || 'untitled'} (${segments.length} segments) — ${notePath}`,
  })

  phase('done', { note: notePath, warnings, provider: provider?.label ?? null })
  return { dir, note: notePath, warnings, segments: segments.length, provider: provider?.label }
}
