export const APP_NAME = 'Bananino'

/** Window footprint with the panel closed — just the character. */
export const WINDOW_SIZES = Object.freeze({
  small: 200,
  medium: 260,
  large: 340,
})

export const DEFAULT_SIZE_KEY = 'medium'

/** Extra room the panel needs, added to the collapsed footprint. */
/** Floor for a measured panel, and the height used before the first measurement. */
export const MIN_PANEL_HEIGHT = 220

/**
 * Extra window width beside the panel, used by the music card.
 *
 * The window grows away from the anchored corner, and the panel and character stay pinned
 * to that corner — so this space appears next to the character without moving it.
 */
export const SIDE_GUTTER = 124

export const PANEL = Object.freeze({
  width: 348,
  height: 320,
  /** How much of the panel the character stands in front of. Kept clear of controls. */
  overlap: 74,
})

export const CORNERS = Object.freeze({
  'bottom-right': { x: 1, y: 1 },
  'bottom-left': { x: 0, y: 1 },
  'top-right': { x: 1, y: 0 },
  'top-left': { x: 0, y: 0 },
})

export const DEFAULT_CORNER = 'bottom-right'

/**
 * Which side of the character the panel opens on. It always grows away from the anchored
 * corner, which is the only way the character can stay put when the window resizes.
 */
export const PANEL_PLACEMENT = Object.freeze({
  'bottom-right': 'above',
  'bottom-left': 'above',
  'top-right': 'below',
  'top-left': 'below',
})

/** Square of screen at the chosen corner that summons the character. */
export const HOT_CORNER_SIZE_PX = 28

/** Cursor must rest in the corner this long before the character appears. */
export const HOT_CORNER_DWELL_MS = 140

/** How long the cursor must be away before the character tucks itself back in. */
export const CONCEAL_DELAY_MS = 900

/**
 * The window is hidden only after the character has animated out. Hiding it immediately
 * is an instant pop, which reads as a glitch rather than an app.
 */
export const CONCEAL_ANIMATION_MS = 300

/**
 * Blur is ignored for this long after the panel opens. Claiming focus from another app
 * is not instantaneous, and a stray blur during the handoff would shut the panel the
 * moment it appeared.
 */
export const BLUR_GRACE_MS = 450

/** Focus must have settled for this long before losing it counts as "clicked away". */
export const FOCUS_SETTLE_MS = 260

/**
 * On close the panel fades/melts first and the window only shrinks once it is gone.
 * Shrinking earlier makes the character ride up with the collapsing area — it looks
 * like the buddy floats away instead of the panel leaving.
 */
export const PANEL_CLOSE_FADE_MS = 240

/** Distance from the screen edge when the character is out and resting. */
export const SCREEN_MARGIN = 22

export const CURSOR_POLL_INTERVAL_MS = 33
export const DRAG_TICK_INTERVAL_MS = 8
export const CURSOR_EPSILON_PX = 1

export const CLIPBOARD_POLL_INTERVAL_MS = 600

/**
 * Pasteboard type markers that mean "do not store this". Password managers set
 * ConcealedType; TransientType and AutoGeneratedType are the related conventions.
 * Matched as substrings because Electron surfaces macOS types under a wrapper name.
 */
export const SECRET_CLIPBOARD_MARKERS = Object.freeze([
  'ConcealedType',
  'TransientType',
  'AutoGeneratedType',
])

export const MAX_RECENT_TASKS = 6

/**
 * Menu entries for the dress-up options. The keys must match the implementations in
 * src/renderer/scene/costumes.js and src/renderer/animation/dances.js.
 */
export const COSTUME_MENU = Object.freeze([
  ['none', 'None'],
  ['party', 'Party hat'],
  ['santa', 'Santa hat'],
  ['headphones', 'Headphones'],
  ['shades', 'Shades'],
  ['crown', 'Crown'],
  ['beanie', 'Beanie'],
])

export const DANCE_MENU = Object.freeze([
  ['bounce', 'Bounce'],
  ['sway', 'Sway'],
  ['twist', 'Twist'],
  ['shimmy', 'Shimmy'],
  ['headbang', 'Headbang'],
  ['spin', 'Spin'],
])

/**
 * Set this to your repository to enable update checks. Releases are read from the GitHub
 * Releases API and the app offers the download — it cannot install one, because
 * Squirrel.Mac requires a code-signed app and this one is not signed yet.
 */
export const UPDATE_REPOSITORY = 'https://github.com/tonitool/bananino'

export const DEFAULT_SHORTCUTS = Object.freeze({
  panel: 'Control+Alt+Space',
  note: 'Control+Alt+N',
  timer: 'Control+Alt+T',
  clips: 'Control+Alt+V',
})

export const IPC = Object.freeze({
  micChunk: 'meeting:mic-chunk',
  micState: 'meeting:mic-state',
  meetingStart: 'meeting:start',
  meetingStop: 'meeting:stop',
  meetingCancel: 'meeting:cancel',
  setInteractive: 'pet:set-interactive',
  dragStart: 'pet:drag-start',
  dragEnd: 'pet:drag-end',
  openMenu: 'pet:open-menu',
  cursorMoved: 'pet:cursor-moved',
  command: 'pet:command',

  panelState: 'panel:state',
  closePanel: 'panel:close',
  togglePanel: 'panel:toggle',
  setPanelHeight: 'panel:height',
  requestSnapshot: 'data:request',
  snapshot: 'data:snapshot',

  saveNote: 'note:save',
  noteMenu: 'note:menu',
  deleteNote: 'note:delete',
  startTimer: 'timer:start',
  stopTimer: 'timer:stop',
  describeTimer: 'timer:describe',
  nudgeTimer: 'timer:nudge',
  addManualTime: 'timer:add-manual',

  copyClip: 'clip:copy',
  deleteClip: 'clip:delete',
  pinClip: 'clip:pin',
  clearClips: 'clip:clear',

  revealData: 'data:reveal',
  setCostume: 'costume:set',

  mocoConnect: 'moco:connect',
  mocoDisconnect: 'moco:disconnect',
  mocoPush: 'moco:push',
  mocoRefresh: 'moco:refresh',
  mocoDiscard: 'moco:discard',
  mocoCatalogue: 'moco:catalogue',

  calendarConnect: 'calendar:connect',
  calendarDisconnect: 'calendar:disconnect',
  calendarJoin: 'calendar:join',
  calendarRefresh: 'calendar:refresh',
})

/*
 * Meeting capture and transcription.
 *
 * Capture goes through a native Core Audio process tap, not Electron: on macOS 26
 * getDisplayMedia's loopback audio track arrives already in the "ended" state (and the
 * system picker yields no audio track at all), so Chromium returns digital silence with
 * no error to catch.
 */
export const MEETING = Object.freeze({
  // Below this level a track is treated as silent and never transcribed: recognisers
  // invent plausible sentences out of silence, and invented content in a meeting record
  // is worse than an acknowledged gap.
  silenceRms: 0.0008,
  // Under this, there is nothing worth transcribing.
  minSeconds: 5,
  maxHours: 4,
  levelSampleMs: 250,
})

export const WHISPER = Object.freeze({
  model: 'ggml-small.bin',
  modelUrl: 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.bin',
  // Checked against the download so a truncated or proxied file fails loudly rather
  // than producing garbage transcripts.
  modelBytes: 487_601_967,
  // Transcribed in the source language; whisper's own --translate mangles exactly the
  // content a meeting note needs (budgets, owners, deadlines), so translation is left
  // to the language model.
  languages: Object.freeze(['auto', 'de', 'en']),
  threads: 4,
})

export const OLLAMA = Object.freeze({
  url: process.env.OLLAMA_URL ?? 'http://127.0.0.1:11434',
  /*
   * Whatever the user already has, in rough order of how well it summarises. Pinning one
   * model would tell most people to download a second copy of something they already
   * have; if none of these are present, any installed model is used instead.
   */
  modelPreference: Object.freeze([
    'qwen3.5', 'llama3.3', 'qwen3', 'llama3.2', 'llama3.1', 'mistral', 'gemma3', 'phi4',
  ]),
  /*
   * Very large local models are not worth it here. A 23 GB model on this hardware took
   * 35 seconds just to answer "OK", and minutes for a real transcript — long enough that
   * summarising timed out entirely. A 6.6 GB model answered the same prompt in 7.
   */
  maxModelBytes: 12_000_000_000,
  timeoutMs: 300_000,
})

export const OPENROUTER = Object.freeze({
  url: 'https://openrouter.ai/api/v1/chat/completions',
  model: 'anthropic/claude-3.5-sonnet',
  timeoutMs: 120_000,
})

/*
 * The published-calendar feed: one HTTPS read per poll, no OAuth anywhere. The link is a
 * bearer secret (Keychain-encrypted at rest); the feed itself is read-only.
 */
export const CALENDAR = Object.freeze({
  pollMs: 60_000,
  feedTimeoutMs: 20_000,
  // Events further out than this are not worth holding in memory.
  horizonHours: 26,
  remindMinutes: 5,
  // A reminder at start still makes sense if the app only catches it a little late.
  startGraceMinutes: 10,
  // The clock prop appears this long before the meeting starts.
  clockLeadMinutes: 15,
})
